version: "3.7"

services:

  nginx:
    container_name: core_web
    restart: on-failure
    image: nginx:stable
    environment:
      CERTBOT_EMAIL: $${{ secrets.NGINX_certbot_email }}
      STAGING: $${{ secrets.NGINX_STAGING }}
      DHPARAM_SIZE: $${{ secrets.NGINX_DHPARAM }}
      RSA_KEY_SIZE: $${{ secrets.NGINX_RSA_KEY_SIZE }}
      ELLIPTIC_CURVE: $${{ secrets.NGINX_ELLIPTIC_CURVE }}
      USE_ECDSA: $${{ secrets.NGINX_USE_ECDSA }}
      RENEWAL_INTERVAL: $${{ secrets.NGINX_RENEWAL_INTERVAL}}
    volumes:
      - ./nginx/user_conf.d:/etc/nginx/user_conf.d
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    container_name: react_app
    restart: on-failure
    environment:
      REACT_APP_API_URL: $${{ secrets.EC2_HOST_DNS }}
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"
    command: >
      sh -c "yarn build && serve -s build"

volumes:
  nginx_secrets: